//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Llibrary_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public string Pasword { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<bool> isUser { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
